development:
  adapter: postgresql
  encoding: unicode
  database: trucksneakers_development


test:
  adapter: postgresql
  encoding: unicode
  database: trucksneakers_test

production:
  adapter: postgresql
  encoding: unicode
  database: trucksneakers_production
